### ISSUE TITLE
Can not open the skill tree in LAN

### ISSUE THREAD

**Issue by connorglasgow** [pufmat/skillsmod#5] opened 2023-04-24 21:59 UTC
I have this mod installed in a custom mod pack I am playing with someone over LAN. When I launch a save I can access the skill tree. When I open to LAN I can access the skill tree. However, the second someone joins the game, I can no longer access the skill tree, but the person who joined _can_ access their own skill tree.

**Comment by pufmat** [comment] 2023-04-25 13:08
Thanks for reporting but I can't reproduce this. What version of game and mod are you using? You can also send game logs and list of mods.

**Comment by connorglasgow** [comment] 2023-04-25 17:40
Just recreated it in a new Curseforge instance.
Minecraft 1.19.2, Forge 43.2.8, Pufferfish skills 0.1.2 is the only installed mod.
[latest.log](https://github.com/pufmat/skillsmod/files/11325302/latest.log)

**Comment by pufmat** [comment] 2023-04-28 17:34
Fixed in 0.2.0

**Closed as completed by pufmat** 2023-04-28 17:34 UTC
